from django.urls import path
from EncMus import Views
from .Views import *
from .Views import eliminar_banda


urlpatterns = [
       path('', inicio, name='Inicio'), 
       path('musicos/', musicos, name='Musicos'),
       path('bandas/', bandas, name='Bandas'),
       path('barandpubs/', barandpubs, name='Barandpubs'),
       path('salasensayo/', salasensayo, name='Salasensayo'),
       path('productores/', productores, name='Productores'),
       path('musicosFormulario/', Views.musicosFormulario, name="musicosFormulario"),
       path('bandasFormulario/', Views.bandasFormulario, name="bandasFormulario"),
       path('barsandpubsFormulario/', Views.barsandpubsFormulario, name="barsandpubsFormulario"),
       path('salasensayoFormulario/', Views.salasensayoFormulario, name="salasensayoFormulario"),
       path('productoresFormulario/', Views.productoresFormulario, name="productoresFormulario"),
       path('busquedaMusicos/', Views.busquedaMusicos, name="busquedaMusicos"),
       path('buscarMusico/', Views.buscarMusicos, name="buscarMusico"),
       path('busquedaBandas/', Views.busquedaBandas, name="busquedaBandas"),
       path('buscarBandas/', Views.buscarBandas, name="buscarBandas"),
       path('busquedaBars/', Views.busquedaBars, name="busquedaBars"),
       path('buscarBars/', Views.buscarBars, name="buscarBars"),
       path('busquedaSala/', Views.busquedaSalas, name="busquedaSala"),
       path('buscarSala/', Views.buscarSalas, name="buscarSala"),
       path('busquedaProductores/', Views.busquedaProductores, name="busquedaProductores"),
       path('buscarProductores/', Views.buscarProductores, name="buscarProductores"),
       path('ListaMusicos/', Views.lista_musicos, name="lista_musicos"),
       path('CreaMusico/', Views.crea_musico, name="crea_musico"),
       path('ListaBandas/', Views.lista_bandas, name="lista_bandas"),
       path('CreaBandas/', Views.crea_banda, name="crea_banda"),
       path('ListaBars/', Views.lista_bars, name="lista_bars"),
       path('CreaBars/', Views.crea_bars, name="crea_bars"),
       path('ListaSalas/', Views.lista_salas, name="lista_salas"),
       path('CreaSalas/', Views.crea_salas, name="crea_salas"),
       path('ListaProd/', Views.lista_prod, name="lista_prod"),
       path('CreaProd/', Views.crea_prod, name="crea_prod"),
       path('EliminaMusico/<int:id>/', Views.eliminar_musico, name="eliminar_musico"),
       path('EliminaBanda/<int:id>/', Views.eliminar_banda, name="eliminar_banda"),
       path('EliminaBar/<int:id>/', Views.eliminar_bars, name="eliminar_bar"),
       path('EliminaSala/<int:id>/', Views.eliminar_salas, name="eliminar_sala"),
       path('EliminaProd/<int:id>/', Views.eliminar_prod, name="eliminar_prod"),
       path('EditaMusico/<int:id>/', Views.editar_musicos, name="editar_musico"),
       path('EditaBanda/<int:id>/', Views.editar_bandas, name="editar_banda"),
       path('EditaBar/<int:id>/', Views.editar_bars, name="editar_bar"),
       path('EditaSalas/<int:id>/', Views.editar_salas, name="editar_sala"),
       path('EditaProd/<int:id>/', Views.editar_prod, name="editar_prod"),
       ]